-- SQL IS CASE INSENSITIVE BUT STANDARD IS TO WRITE IN ALL CAPS
-- * WILL SELECT EVERYTHING

-- SELECTING SPECIFIC COLUMNS BY PROVIDING COLUMN NAMES AND SEPARATING BY COMMA
-- SELECT * FROM BREAKFAST; A TABLE THAT DOES NOT EXIST

-- EXPLORING THRU THE DB
-- SELECT EVERY COUNTRY

SELECT * FROM COUNTRIES;

-- SELECT EVERY DEPARTMENT
    SELECT * FROM DEPARTMENTS;

-- SELECT EVERY JOB
    SELECT * FROM JOBS;

-- SELECT EVERY REGION
    SELECT * FROM REGIONS;

-- SELECT EVERY JOB_HISTORY
    SELECT * FROM JOB_HISTORY;

-- DISPLAY ONLY THE FIRST NAME COLUMN OF EMPLOYEE TABLE
    SELECT FIRST_NAME FROM EMPLOYEES;

-- DISPLAY ONLY FIRST_NAME LAST_NAME COLUMNS OF EMPLOYEES TABLE

-- IF YOU WANT TO DISPLAY ONLY THE FIRST_NAME LAST_NAME AND SALARY COLUMNS OF EMPLOYEES TABLE BY USING A COMMA TO SEPARATE

-- DISPLAY COUNTRY_NAME AND REGION_ID FROM COUNTRIES TABLE

-- DISPLAY JOB_ID AND JOB_TITLE FROM THE JOBS TABLE

-- DISPLAY THE FIRST_NAME AND SALARY FROM THE EMPLOYEES TABLE
-- BUT SHOW THE SALARY COLUMN AS MONEY FOR COLUMN NAME

-- DISPLAY FIRST_NAME AND LAST_NAME FROM EMPLOYEES TABLE
-- DISPLAY THE COLUMN AS GIVEN_NAME, FAMILY_NAME

-- ONLY DISPLAY NON-DUPLICATE ROWS IN THE TABLE
-- DISPLAY ALL UNIQUE FIRST NAMES IN EMPLOYEE TABLE

-- DISPLAY ALL UNIQUE JOB ID FROM EMPLOYEES TABLE

-- GET SOMETHING BASED ON A CONDITION
-- 'WHERE' IS USED WHEN YOU WANT TO FILTER BY A CONDITION
-- DISPLAY FIRST_NAME AND LAST_NAME WHERE THE FIRST_NAME IS STEVEN

-- DISPLAY FIRST_NAME AND SALARY IF THE SALARY IS MORE THAN 10000

-- DISPLAY FIRST_NAME AND EMAIL AND SALARY IF THE SALARY IS MORE THAN 5000

-- DISPLAY FIRST_NAME AND SALARY AND COMMISSION_PCT IF THE SALARY IS MORE THAN OR EQUAL TO 7000

-- DISPLAY FIRST_NAME AND DEPARTMENT_ID AND SALARY IF THE SALARY IS LESS THAN OR EQUAL TO 5000

-- DISPLAY FIRST_NAME AND LAST_NAME AND SALARY IF THE SALARY IS MORE THAN 10000 OR LESS THAN 5000

-- DISPLAY FIRST_NAME AND LAST_NAME AND SALARY IF THE SALARY IS LESS THAN 10000 OR MORE THAN 5000

-- DISPLAY FIRST_NAME, SALARY IF THE DEPARTMENT_ID IS 60 AND SALARY IS MORE THAN 7000

-- DISPLAY FIRST_NAME, SALARY IF THE DEPARTMENT_ID IS 60 AND SALARY DOES NOT EQUAL(<> || !=) 6000

-- DISPLAY FIRST_NAME AND SALARY IF THE SALARY IS LESS THAN 10000 AND SALARY IS MORE THAN 5000 = WHERE SALARY BETWEEN 5000 AND 10000

-- DISPLAY ALL EMPLOYEE INFO IF THE EMPLOYEE_ID IS BETWEEN 110 AND 120

-- DISPLAY ALL EMPLOYEES WITH EMPLOYEE_ID OF 110, 112, 115, 116

-- WRITE ABOVE QUERY MUCH SIMPLER BY USING IN(PROVIDE VALUES LIKE AN INTEGER OR STRING SURROUNDED BY '')

-- DISPLAY FIRST_NAME, JOB_ID FROM EMPLOYEES
-- IF THE JOB IDS ARE AD_ASST, FI_MGR OR FI_ACCOUNT

-- DISPLAY ALL DEPARTMENT INFORMATION FROM DEPARTMENT TABLE
-- IF THE DEPARTMENT_NAME ARE AS BELOW
-- IT, PUBLIC RELATIONS, SALES, EXECUTIVE

-- DISPLAY ALL EMPLOYEES FIRST_NAME AND COMMISSION_PCT IF THE COMMISSION_PCT IS OR IS NOT NULL

-- DISPLAY ALL EMPLOYEES FIRST_NAME AND COMMISSION_PCT
-- IF THE COMMISSION_PCT VALUE IS NOT NULL
-- AND COMMISSION_PCT IS GREATER THAN 0.2

-- HOW TO SORT(ORDER) THE RESULT BY CERTAIN COLUMN NAME OR COLUMN INDEX
-- WE CAN USE ORDER BY COLUMN NAME OR ORDER BY COLUMN INDEX
-- SORT THE RESULT BY FIRST_NAME COLUMN

-- SORT THE RESULT BY FIRST_NAME COLUMN ASCENDING ORDER(LOW TO HIGH)

-- SORT THE RESULT BY FIRST_NAME COLUMN DESCENDING ORDER(HIGH TO LOW)

-- SORT THE RESULT BY SALARY COLUMN DESCENDING ORDER(HIGH TO LOW)

-- SORT THE RESULT BY SALARY COLUMN ASCENDING ORDER(LOW TO HIGH)

-- DISPLAY EVERYTHING IN EMPLOYEE TABLE IF THE DEPARTMENT_ID IS 80
-- SORT THE RESULT BY SALARY_COLUMN DESCENDING ORDER

-- ORDER BY COLUMN INDEX(YOU JUST WRITE SOMETHING LIKE 2)

-- ORDER THE RESULT BY FIRST COLUMN DESC

-- USE INDEX TO SORT BY SALARY COLUMN ASC ORDER

-- USING PARTIAL LOGIC WITH WILDCARD: LIKE '%'
-- FIND ALL EMPLOYEE NAMES THAT START WITH A

-- FIND ALL FIRST NAMES THAT END WITH A THIS IS CASE SENSITIVE

-- FIND ALL EMPLOYEES FIRST_NAME THAT START WITH L AND ENDS WITH 'L%a'

-- FIND ALL EMPLOYEE FIRST_NAME THAT CONTAINS %V%
-- FIND ALL EMPLOYEE FIRST_NAME THAT CONTAINS B
-- FIND ALL EMPLOYEE FIRST_NAME THAT CONTAINS C

-- FIND ALL PHONE_NUMBERS THAT START WITH 650

-- FIND ALL PHONE_NUMBER THAT CONTAINS 44

-- FIND ALL JOB_ID THAT END WITH CLERK EMPLOYEES TABLE

-- FIND EMPLOYEES WHOSE NAMES START WITH T AND FOLLOWED BY A SINGLE CHARACTER __

-- FIND EMPLOYEES FIRST_NAME THAT START WITH AN A AND HAVE EXACTLY 4 CHARACTERS TOTAL
