SELECT * FROM COUNTRIES;

SELECT * FROM EMPLOYEES;

SELECT * FROM COUNTRIES;

SELECT * FROM DEPARTMENTS;

SELECT * FROM LOCATIONS;

SELECT * FROM JOBS;

SELECT * FROM JOB_HISTORY;

SELECT FIRST_NAME FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES;

SELECT COUNTRY_NAME, REGION_ID FROM COUNTRIES;

SELECT JOB_ID, JOB_TITLE FROM JOBS;

SELECT FIRST_NAME, SALARY AS MONEY FROM EMPLOYEES;

SELECT FIRST_NAME AS GIVEN_NAME,
       LAST_NAME AS FAMILY_NAME
FROM EMPLOYEES;

SELECT DISTINCT FIRST_NAME FROM EMPLOYEES;

SELECT DISTINCT JOB_ID FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE FIRST_NAME = 'Steven';

SELECT FIRST_NAME, SALARY FROM EMPLOYEES WHERE SALARY > 10000;

SELECT FIRST_NAME, EMAIL, SALARY FROM EMPLOYEES WHERE SALARY > 5000;

SELECT FIRST_NAME,
       SALARY,
       COMMISSION_PCT
FROM EMPLOYEES
WHERE SALARY >= 7000;

SELECT FIRST_NAME,
       DEPARTMENT_ID,
       SALARY
FROM EMPLOYEES
WHERE SALARY <= 5000;

SELECT FIRST_NAME,
       LAST_NAME,
       SALARY
FROM EMPLOYEES
WHERE SALARY > 10000 OR SALARY < 5000;

SELECT FIRST_NAME,
       LAST_NAME,
       SALARY
FROM EMPLOYEES
WHERE SALARY < 10000 OR SALARY > 5000;

SELECT FIRST_NAME,
       SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60 AND SALARY > 7000;

SELECT FIRST_NAME,
       SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60 AND SALARY != 6000;

SELECT FIRST_NAME,
       SALARY
FROM EMPLOYEES
WHERE SALARY BETWEEN 5000 AND 10000;

SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID BETWEEN 110 AND 120;

SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID IN('110', '112', '115', '116');

SELECT FIRST_NAME,
       JOB_ID
FROM EMPLOYEES
WHERE JOB_ID
          IN('AD_ASST', 'FI_MGR', 'FI_ACCOUNT');

SELECT *
FROM DEPARTMENTS
WHERE DEPARTMENT_NAME
IN('IT', 'Public Relations', 'Sales', 'Executive');

SELECT FIRST_NAME,
       LAST_NAME,
       COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL OR COMMISSION_PCT IS NULL;

SELECT FIRST_NAME,
       COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
AND COMMISSION_PCT < 0.2;

SELECT *
FROM EMPLOYEES
         ORDER BY FIRST_NAME ASC;

SELECT * FROM EMPLOYEES
ORDER BY FIRST_NAME DESC;

SELECT * FROM EMPLOYEES
ORDER BY SALARY DESC;

SELECT * FROM EMPLOYEES
ORDER BY SALARY ASC;

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID = 80
ORDER BY SALARY DESC;

SELECT * FROM EMPLOYEES
ORDER BY 1;

SELECT * FROM EMPLOYEES
ORDER BY 8;

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'A%';

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%a';

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'L%a';

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%v%';

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%b%';

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%c%';

SELECT * FROM EMPLOYEES
WHERE PHONE_NUMBER LIKE '650%';

SELECT * FROM EMPLOYEES
WHERE PHONE_NUMBER LIKE '%44%';

SELECT * FROM JOBS
WHERE JOB_ID LIKE '%CLERK';

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'T_';

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'A____';













