SELECT * FROM EMPLOYEES WHERE SALARY IN(5000, 7000, 11000);

SELECT * FROM COUNTRIES WHERE COUNTRY_ID IN('EG', 'FR', 'IL');

SELECT * FROM JOBS ORDER BY MAX_SALARY DESC;

SELECT * FROM JOBS WHERE JOB_TITLE LIKE '%Manager';

SELECT * FROM JOBS WHERE MIN_SALARY BETWEEN 8000 AND 15000 AND JOB_TITLE NOT LIKE '%Manager';

SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IS NULL;

SELECT * FROM DEPARTMENTS WHERE MANAGER_ID IS NULL;

SELECT * FROM LOCATIONS WHERE COUNTRY_ID IN('US', 'UK');

SELECT * FROM COUNTRIES WHERE REGION_ID = 1 AND COUNTRIES.COUNTRY_NAME <> 'Belgium';

SELECT FIRST_NAME || ' ' || LAST_NAME FROM EMPLOYEES;




