SELECT * FROM EMPLOYEES WHERE SALARY IN(5000, 7000, 11000);

SELECT * FROM COUNTRIES WHERE COUNTRY_ID IN('EG', 'FR', 'IL');

SELECT * FROM JOBS ORDER BY MAX_SALARY DESC;

SELECT * FROM JOBS WHERE JOB_TITLE LIKE '%Manager';

SELECT * FROM JOBS WHERE MIN_SALARY BETWEEN 8000 AND 15000 AND JOB_TITLE NOT LIKE '%Manager';

SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IS NULL;

SELECT * FROM DEPARTMENTS WHERE MANAGER_ID IS NULL;

SELECT * FROM LOCATIONS WHERE COUNTRY_ID IN('US', 'UK');

SELECT * FROM COUNTRIES WHERE REGION_ID = 1 AND COUNTRIES.COUNTRY_NAME <> 'Belgium';

SELECT FIRST_NAME || ' ' || LAST_NAME FROM EMPLOYEES;

SELECT FIRST_NAME || ' MAKES ' || SALARY FROM EMPLOYEES;

SELECT FIRST_NAME, SALARY, SALARY + 5000 FROM EMPLOYEES;

SELECT FIRST_NAME, SALARY, SALARY - 2000 FROM EMPLOYEES;

SELECT FIRST_NAME, SALARY * 12 FROM EMPLOYEES;

SELECT UPPER(FIRST_NAME) FROM EMPLOYEES;

SELECT LOWER(FIRST_NAME), LENGTH(FIRST_NAME) FROM EMPLOYEES;

SELECT FIRST_NAME FROM EMPLOYEES WHERE LENGTH(FIRST_NAME) = 6;

SELECT FIRST_NAME FROM EMPLOYEES WHERE FIRST_NAME LIKE '%a%' OR FIRST_NAME LIKE '%A%';

SELECT FIRST_NAME FROM EMPLOYEES WHERE UPPER(FIRST_NAME) LIKE '%A%';
SELECT FIRST_NAME FROM EMPLOYEES WHERE LOWER(FIRST_NAME) LIKE '%a%';

SELECT FIRST_NAME, SALARY, ROUND(SALARY) FROM EMPLOYEES;






