SELECT DEPARTMENT_ID, ROUND(AVG(SALARY))
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY) > 8000;


SELECT UPPER(FIRST_NAME),
       LENGTH(LAST_NAME),
       LENGTH(FIRST_NAME || LAST_NAME),
       FIRST_NAME || ' ' || LAST_NAME AS "FULL NAME"
FROM EMPLOYEES
ORDER BY 3;

SELECT FIRST_NAME, DEPARTMENT_ID FROM EMPLOYEES
WHERE FIRST_NAME = 'Steven' AND LAST_NAME = 'King';

SELECT DEPARTMENT_ID, DEPARTMENT_NAME
FROM DEPARTMENTS
WHERE DEPARTMENT_ID = 90;

SELECT EMPLOYEES.FIRST_NAME,
       DEPARTMENTS.DEPARTMENT_ID,
       DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES
INNER JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

SELECT E.FIRST_NAME,
       D.DEPARTMENT_ID,
       D.DEPARTMENT_NAME
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;