-- DAY 1

-- SQL IS CASE INSENSITIVE BUT STANDARD IS TO WRITE IN ALL CAPS
-- * WILL SELECT EVERYTHING

-- SELECTING SPECIFIC COLUMNS BY PROVIDING COLUMN NAMES AND SEPARATING BY COMMA
-- SELECT * FROM BREAKFAST; A TABLE THAT DOES NOT EXIST

-- EXPLORING THRU THE DB
-- SELECT EVERY COUNTRY

-- SELECT EVERY DEPARTMENT

-- SELECT EVERY JOB
